sudo: false
language: python
python:
  - "2.7"
install:
    - pip install -U coverage coveralls
    - pip install -U six==1.10.0
    - python bootstrap.py
    - bin/buildout
script:
    - coverage run bin/test -pvc
after_success:
    - coveralls
notifications:
    email: tseaver@palladion.com
cache:
    pip: true
    directories:
      - eggs/
