sudo: false
dist: trusty
language: python
cache:
    directories:
        - $TRAVIS_BUILD_DIR/eggs
python:
  - "2.7"
  - "3.6"
install:
    - pip install zc.buildout
    - buildout
script:
    - bin/test -pvc
notifications:
    email: tseaver@palladion.com
