sudo: false
dist: trusty
language: python
cache:
    directories:
        - $TRAVIS_BUILD_DIR/eggs
python:
  - "2.7"
  - "3.6"
install:
    - pip install zc.buildout
# six version should be the same as the one in Zope versions file
    - pip install six==1.10.0
    - buildout
script:
    - bin/test -pvc
notifications:
    email: tseaver@palladion.com
